name: opendungeons
version: "0.8.0+ogre13"
confinement: strict
summary: OpenDungeons
base: core20
description: Open source game inspired by Dungeon Keeper - Dark, damp and dangerous.

apps:
    opendungeons:
        command: bin/desktop-launch $SNAP/usr/games/opendungeons
        environment:
            CEGUI_MODULE_DIR: $SNAP/usr/lib/cegui-0.9999
        plugs: [opengl, x11, pulseaudio, network, network-bind]
        desktop: usr/share/applications/opendungeons.desktop
parts:
    desktop-glib-only:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: glib-only
        plugin: make
    ogre:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DOGRE_BUILD_DEPENDENCIES=FALSE
            - -DOGRE_BUILD_RENDERSYSTEM_GL=TRUE
            - -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=TRUE
            - -DOGRE_RESOURCEMANAGER_STRICT=0
            # stuff we dont need
            - -DOGRE_BUILD_RENDERSYSTEM_GLES2=FALSE
            - -DOGRE_BUILD_TOOLS=FALSE
            - -DOGRE_BUILD_SAMPLES=FALSE
            - -DOGRE_BUILD_PLUGIN_FREEIMAGE=FALSE
            - -DOGRE_BUILD_PLUGIN_EXRCODEC=FALSE
            - -DOGRE_BUILD_PLUGIN_BSP=FALSE
            - -DOGRE_BUILD_PLUGIN_PCZ=FALSE
            - -DOGRE_BUILD_PLUGIN_DOT_SCENE=FALSE
            - -DOGRE_BUILD_COMPONENT_JAVA=FALSE
            - -DOGRE_BUILD_COMPONENT_VOLUME=FALSE
            - -DOGRE_BUILD_COMPONENT_PAGING=FALSE
            - -DOGRE_BUILD_COMPONENT_TERRAIN=FALSE
            - -DOGRE_BUILD_COMPONENT_PROPERTY=FALSE
            - -DOGRE_BUILD_COMPONENT_MESHLODGENERATOR=FALSE
            - -DCMAKE_INSTALL_PREFIX=/usr/
        source: https://github.com/OGRECave/ogre.git
        source-tag: master
        source-depth: 1
        build-packages:
            - libxrandr-dev
            - libfreetype6-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - g++
        stage-packages:
            - libfreetype6
            - libgl1
            - libxrandr2
            - libegl1
    cegui:
        plugin: cmake
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_FLAGS=-std=c++11
            - -DCEGUI_BUILD_RENDERER_OPENGL=FALSE
            - -DCEGUI_BUILD_RENDERER_OPENGLES=FALSE
            - -DCEGUI_BUILD_RENDERER_OPENGL3=FALSE
            - -DCEGUI_BUILD_IMAGECODEC_FREEIMAGE=FALSE # we use ogre
            - -DCEGUI_OPTION_DEFAULT_IMAGECODEC=OgreRenderer-0
            - -DCEGUI_SAMPLES_ENABLED=FALSE
        build-environment:
            - CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH:$SNAPCRAFT_STAGE/usr
        source: https://github.com/paroj/cegui.git
        source-depth: 1
        source-tag: v0
        build-packages:
            - librapidxml-dev
        after: [ogre]
    opendungeons:
        plugin: cmake
        source: https://github.com/paroj/OpenDungeons.git
        source-tag: snapcraft
        source-depth: 1
        override-pull: |
            snapcraftctl pull
            sed -i -e 's|if(CMAKE_INSTALL_PREFIX|if(""|g' CMakeLists.txt
        cmake-parameters:
            - -DCMAKE_BUILD_TYPE=Release
            - -DCMAKE_INSTALL_PREFIX=/usr/
            - -DCMAKE_CXX_FLAGS=-std=c++11
            - -DOD_TREAT_WARNINGS_AS_ERRORS=FALSE
        build-environment:
            - CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH:$SNAPCRAFT_STAGE/usr
        override-build: |
            snapcraftctl build
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/etc/opendungeons/plugins.cfg # drop stage prefix
            sed -i -e 's|/.*/stage||g' $SNAPCRAFT_PART_INSTALL/usr/share/games/opendungeons/resources.cfg # drop stage prefix
        build-packages:
            - libsfml-dev
            - libois-dev
            - libboost-thread-dev
            - libboost-locale-dev
            - libboost-filesystem-dev
            - libboost-program-options-dev
        stage-packages:
            - libsfml-window2.5
            - libsfml-audio2.5
            - libsfml-system2.5
            - libsfml-network2.5
            - libboost-thread1.71.0
            - libboost-program-options1.71.0
            - libboost-filesystem1.71.0
            - libboost-system1.71.0
            - libboost-locale1.71.0
            - libboost-chrono1.71.0
            - libois-1.3.0v5
            - libpulse0
        after: [ogre, cegui, desktop-glib-only]
